PFOSIS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('fondos.urls')),

]

fondos/urls.py
from django.urls import path

from  fondos.views import *
app_name = 'fondos'
urlpatterns = [

    path('fondo/<int:pk>',publicacion_view.as_view(),name='index'),
    path('crear_publicacion', publicacion_create.as_view(), name='crear'),
    path('', tipo_view.as_view(), name='tipo'),
    path('publicacion/<int:pk>', publicacion_object.as_view(), name="ver"),
]

fondos/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
import calendar,cmath
from django.contrib.auth.models import AbstractBaseUser


# Create your models here.



class usuario(AbstractBaseUser):
    rut = models.CharField(max_length=20,unique=True,null=False,verbose_name="Documento Chileno de identificación")
    nombres = models.CharField(max_length=100,verbose_name="Nombres")
    rol = models.ForeignKey('rol',verbose_name="Rol",on_delete=models.PROTECT)

    apellidos = models.CharField(max_length=100,verbose_name="Apellidos")
    fecha_creado = models.DateTimeField(auto_created=True,verbose_name="Fecha de creación")
    fecha_editado = models.DateTimeField(auto_now=True,verbose_name="Fecha de Ultima Edición")

    USERNAME_FIELD = 'rut'
    REQUIRED_FIELDS = ['rut','rol']


    def nombre_completo(self):
        nombre_comm = self.nombres+" "+self.apellidos
        return nombre_comm

    def __str__(self):
       return "{} - {} - {}".format(
            self.nombre_completo(),
            self.rut,
            self.rol
        )

class dimensiones(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
       return "{}".format(
            self.nombre
        )

class publicaciones(models.Model):
    nombre_fondo = models.CharField(max_length=200,null=False,verbose_name="Nombre del Fondo")
    dimension = models.ForeignKey('dimensiones',verbose_name="Dimensión",on_delete=models.PROTECT)
    descripcion = models.CharField(max_length=1000,null=True,verbose_name='descripcion')
    autor = models.ForeignKey('auth.User',verbose_name="Autor",on_delete=models.PROTECT)
    objetivo = models.CharField(max_length=300,null=True,verbose_name="Objetivo")
    enlace = models.CharField(max_length=200,verbose_name="Link")
    fecha_inicio = models.DateTimeField(verbose_name="Fecha inicio")
    fecha_termino = models.DateTimeField(verbose_name="Fecha termino")
    activo = models.BooleanField(default=True)


    def __str__(self):
       return "{} - {} - {} - {}".format(
            self.nombre_fondo,
            self.dimension,
            self.autor,
            self.fecha_termino
        )
    def cambio_de_estado(self):
        if self.fecha_termino < timezone.now():
            print("Termino")


    def dias_que_faltan(self):
        dias = "Quedan {} días para que expire el fondo".format(str(self.fecha_termino.day - timezone.now().day))
        if self.fecha_termino < timezone.now():
            dias = "Ya expiro el fondo"
        if self.fecha_inicio > timezone.now():
            dias = "Aun no empiezan las postulaciones"
        return dias
    def porcentajes(self):
        p = round(((  timezone.now() - self.fecha_inicio) / (self.fecha_termino - self.fecha_inicio))*100 )
        if p > 100:
            p = 100
        elif p < 0:
            p = 0
        return p



class estado(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return "{}".format(
            self.nombre
        )
class adjudicarse_fondo(models.Model):

    subscriptor = models.ForeignKey('usuario',on_delete=models.PROTECT)
    publicacion = models.ForeignKey('publicaciones',on_delete=models.PROTECT)
    estado = models.ForeignKey('estado',on_delete=models.PROTECT)

class rol(models.Model):
    tipo = models.CharField(max_length=100)

    def __str__(self):
       return "{}".format(
            self.tipo
        )
usuario = get_user_model()

fondos/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from fondos.forms import *
from django.utils import timezone
from django.views.generic import TemplateView, ListView,CreateView, DetailView
from fondos.models import *
from django.urls import reverse,reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
# Create your views here.
from django.contrib.auth import get_user_model


class publicacion_view(ListView):
    model = publicaciones
    template_name = 'index.html'
    paginate_by = 50
    def get_context_data(self,*args, **kwargs):
        ctx =super().get_context_data(*args,**kwargs)
        slug= self.kwargs['pk']
        ctx['publicaciones2'] = publicaciones.objects.filter(dimension=slug)
        return ctx

class publicacion_object(DetailView):
    model = publicaciones
    object_name = "publicacion"
    template_name = 'publicaciones/ver_publicacion.html'
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        slug = self.kwargs['pk']
        ctx['actividades2'] = publicaciones.objects.filter(pk=slug)
        return ctx

class publicacion_create(CreateView):
    model = publicaciones
    template_name = 'publicaciones/crear_publicacion.html'
    form_class = publicacionForm

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('fondos:tipo')



class tipo_view(ListView):
    model = dimensiones
    template_name = 'home.html'
    queryset = dimensiones.objects.all()

fondos/templates/base.html
{% load static %}
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<html lang="en">
<head>
 <link rel="shortcut icon" href="{%  static 'assets/favicon.png' %}">
 <link rel="" href="{%  static 'assets/favicon.png' %}">
 <!-- Bootstrap core CSS -->
    <link href="{% static 'directorio/css/bootstrap.min.css' %}" rel="stylesheet">
<link
  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css"
  rel="stylesheet"  type='text/css'>
    <link href="{% static 'directorio/css/alertify.min.css' %}" rel="stylesheet">
    <link href="{% static 'directorio/css/bootstrap.rtl.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
     <link href="{% static 'directorio/css/base.css' %}" rel="stylesheet">


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

    <meta name="author" content="">


    <title> {% block titulo_pagina %}{% endblock %} </title>
 <div class="arrow">
<button type="button" style="scroll-behavior: auto;position: fixed;" class="btn-success fixed-bottom "  id="btn-back-to-top">
  <i class="fa fa-arrow-up  "></i>
</button>
</div>

</head>

<body>
<div style="background-image: linear-gradient( 109.6deg,  rgba(242, 159, 5, 1) 11.2%, rgba(242, 159, 5, 1) 91.1% );" class="header py-5 bg-light rounded ">
            <div class="container">
                <div class="text-center my-5">

                    <h1 class="fw-bolder ">
                        <i class="fa fa-calendar-o"></i>
                        ¡Queltehue Tu canal social!
                    </h1>
                    <span >Bienvenido a tu pagina de información para fondos concursables</span>
                </div>
            </div>

        </div>

{% include 'partials/navbar.html' %}

<!-- Begin page content -->
<div class="container">
    {% block contenido %}
    {% endblock %}
    <br>

</div>

{% include 'partials/footer.html' %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'directorio/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'directorio/js/popper.min.js' %}"></script>
<script src="{% static 'directorio/js/bootstrap.min.js' %}"></script>
<script src="{% static 'directorio/js/alertify.min.js' %}"></script>

{% block extra_js %}
 <script>
 var element = document.getElementById("btn-back-to-top");
element.onclick = function(event) {
     window.scrollTo({ top: 0, behavior: 'smooth' });
}

 </script>
{% endblock %}

</body>
</html>

fondos/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}
<H1 style="padding-bottom: 50px;text-align: center;" class="card-title " >

    Selecciona la categoría que quieres buscar</H1>




<div class="row ">
{% for i in object_list %}

<div style="padding-bottom: 10px" class="col-sm-6 col-xl-4 ">
<a href="{% url 'fondos:index' i.pk %}">
		<div class="card bg-success">
			<div class="card-body d-flex justify-content-between align-items-start pb-3 ">

						 <b class="text-white align-text-right">{{i.nombre}}</b>
                <br>
            </div>
        </div>
    </a>
</div>

{% endfor %}
</div>
{% endblock %}

fondos/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% load tz %}
{% block contenido %}
<H1 style="padding-bottom: 50px;text-align: center;" class="card-title " >

    Encuentra los fondos concursables disponibles para tu region</H1>


<div class="row">

	{% for i in publicaciones2 %}
	<div style="padding-bottom: 10px" class="col-sm-6 col-xl-4">
		<div class="card border-info">
			<div class="card-body d-flex justify-content-between align-items-start pb-3">
				<div>
					<a href="{% url 'fondos:ver' i.pk %}" class="text-capitalize">
						 {{i.nombre_fondo}} </a>
					<span class="badge badge-success align-text-bottom ml-1">{{i.dimension}}</span>
					<div class="text-muted small mt-1"></div>
                    <b class="badge badge-light my-xl-1">Enlace para postular al fondo:</b>
                    <a href="https://{{ i.enlace }}" class="badge badge-dark">{{ i.enlace }}</a>
				</div>



			</div>
			<div class="progress rounded-0" style="height: 3px;">
				<div class="progress-bar" style=" width: {{ i.porcentajes }}%;"></div>
			</div>
			

			<div class="card-body pt-0">
				<div class="row">
                    <div class="col">
						<div class="text-muted small">Estado del fondo</div>
						<div class=" {% if localtime > i.fecha_termino %}alert-danger{% else %} alert-success{% endif %} rounded font-weight-normal">{{i.dias_que_faltan}}</div>
					</div>
					<div class="col">
						<div class="text-muted small">Fecha inicio</div>
						<div class="font-weight-normal">{{i.fecha_inicio}}</div>
					</div>
					<div class="col">
						<div class="text-muted small">Fecha término</div>
						<div class="font-weight-normal">{{i.fecha_termino}}</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
</div>

{% endblock %}