PFOSIS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('fondos.urls')),

]

fondos/urls.py
from django.urls import path

from  fondos.views import *
app_name = 'fondos'
urlpatterns = [

    path('fondo/<int:pk>',publicacion_view.as_view(),name='index'),
    path('crear_publicacion', publicacion_create.as_view(), name='crear'),
    path('', tipo_view.as_view(), name='tipo'),
    path('publicacion/<int:pk>', publicacion_object.as_view(), name="ver"),
]

fondos/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
import calendar,cmath
from django.contrib.auth.models import AbstractBaseUser


# Create your models here.



class usuario(AbstractBaseUser):
    rut = models.CharField(max_length=20,unique=True,null=False,verbose_name="Documento Chileno de identificación")
    nombres = models.CharField(max_length=100,verbose_name="Nombres")
    rol = models.ForeignKey('rol',verbose_name="Rol",on_delete=models.PROTECT)

    apellidos = models.CharField(max_length=100,verbose_name="Apellidos")
    fecha_creado = models.DateTimeField(auto_created=True,verbose_name="Fecha de creación")
    fecha_editado = models.DateTimeField(auto_now=True,verbose_name="Fecha de Ultima Edición")

    USERNAME_FIELD = 'rut'
    REQUIRED_FIELDS = ['rut','rol']


    def nombre_completo(self):
        nombre_comm = self.nombres+" "+self.apellidos
        return nombre_comm

    def __str__(self):
       return "{} - {} - {}".format(
            self.nombre_completo(),
            self.rut,
            self.rol
        )

class dimensiones(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
       return "{}".format(
            self.nombre
        )

class publicaciones(models.Model):
    nombre_fondo = models.CharField(max_length=200,null=False,verbose_name="Nombre del Fondo")
    dimension = models.ForeignKey('dimensiones',verbose_name="Dimensión",on_delete=models.PROTECT)
    descripcion = models.CharField(max_length=1000,null=True,verbose_name='descripcion')
    autor = models.ForeignKey('auth.User',verbose_name="Autor",on_delete=models.PROTECT)
    objetivo = models.CharField(max_length=300,null=True,verbose_name="Objetivo")
    enlace = models.CharField(max_length=200,verbose_name="Link")
    fecha_inicio = models.DateTimeField(verbose_name="Fecha inicio")
    fecha_termino = models.DateTimeField(verbose_name="Fecha termino")
    activo = models.BooleanField(default=True)


    def __str__(self):
       return "{} - {} - {} - {}".format(
            self.nombre_fondo,
            self.dimension,
            self.autor,
            self.fecha_termino
        )
    def cambio_de_estado(self):
        if self.fecha_termino < timezone.now():
            print("Termino")


    def dias_que_faltan(self):
        dias = "Quedan {} días para que expire el fondo".format(str(self.fecha_termino.day - timezone.now().day))
        if self.fecha_termino < timezone.now():
            dias = "Ya expiro el fondo"
        if self.fecha_inicio > timezone.now():
            dias = "Aun no empiezan las postulaciones"
        return dias
    def porcentajes(self):
        p = round(((  timezone.now() - self.fecha_inicio) / (self.fecha_termino - self.fecha_inicio))*100 )
        if p > 100:
            p = 100
        elif p < 0:
            p = 0
        return p



class estado(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return "{}".format(
            self.nombre
        )
class adjudicarse_fondo(models.Model):

    subscriptor = models.ForeignKey('usuario',on_delete=models.PROTECT)
    publicacion = models.ForeignKey('publicaciones',on_delete=models.PROTECT)
    estado = models.ForeignKey('estado',on_delete=models.PROTECT)

class rol(models.Model):
    tipo = models.CharField(max_length=100)

    def __str__(self):
       return "{}".format(
            self.tipo
        )
usuario = get_user_model()

fondos/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from fondos.forms import *
from django.utils import timezone
from django.views.generic import TemplateView, ListView,CreateView, DetailView
from fondos.models import *
from django.urls import reverse,reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
# Create your views here.
from django.contrib.auth import get_user_model


class publicacion_view(ListView):
    model = publicaciones
    template_name = 'index.html'
    paginate_by = 50
    def get_context_data(self,*args, **kwargs):
        ctx =super().get_context_data(*args,**kwargs)
        slug= self.kwargs['pk']
        ctx['publicaciones2'] = publicaciones.objects.filter(dimension=slug)
        return ctx

class publicacion_object(DetailView):
    model = publicaciones
    object_name = "publicacion"
    template_name = 'publicaciones/ver_publicacion.html'
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        slug = self.kwargs['pk']
        ctx['actividades2'] = publicaciones.objects.filter(pk=slug)
        return ctx

class publicacion_create(CreateView):
    model = publicaciones
    template_name = 'publicaciones/crear_publicacion.html'
    form_class = publicacionForm

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('fondos:tipo')



class tipo_view(ListView):
    model = dimensiones
    template_name = 'home.html'
    queryset = dimensiones.objects.all()

fondos/templates/partials/footer.html
<footer class="footer" color="#fff">
    <div class="container text-center">
        <span class="text-muted"> Centro de Innovación y emprendimiento - UNACH</span>


                    <a style="padding-right:20px;padding-left: 20px; " href="https://www.instagram.com" class="footer-link"><i class="fa fa-youtube-play fa-lg"></i></a>

                    <a style="padding-right:20px " href="https://www.instagram.com" class="footer-link"><i class="fa fa-instagram fa-lg"></i></a>

                    <a style="padding-right:20px " href="https://www.facebook.com" class="footer-link"><i class="fa fa-facebook-official fa-lg"></i></a>




    </div>
</footer>

fondos/templates/partials/navbar.html
{% load static %}
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-transparent">

<div>
    <a class="navbar-brand " href="{% url 'fondos:tipo' %}" > <img width="90" height="75" src="{%  static 'assets/favicon.png' %}" > </a>



</div>
<div>
<div class="callout">

  <div class="callout-container">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>

    <p>Clickea en el Queltehue para volver al inicio</p>
  </div>
</div>
</div>
    <div class="ml-auto">


            {% if request.user.is_authenticated %}
                <ul class="nav-item dropdown text-white align-content-end">
                    <a class="nav-link dropdown-toggle text-white"
                       data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user text-white"></i> {{ request.user }}
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="/admin/">
                            <i class="fa fa-gear"></i>
                            Administración
                        </a>
                         <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'fondos:crear' %}">
                            <i class="fa fa-angellist"></i>
                           Crear nuevo fondo
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">
                            <i class="fa fa-sign-out"></i>
                            Cerrar Sesión
                        </a>
                         </div>
                </ul>
                {% else %}
                  <ul >
                <div class="dropdown-menu"></div>
                <a class="dropdown-item" href="{% url 'login' %}">
                    <i class="fa fa-sign-in"></i>
                    Iniciar Sesión
                </a>

                </ul>

            {% endif %}
        </ul>
    </div>

</nav>

<script>
    $(document).ready(function(){
        var scroll_pos = 0;
        $(document).scroll(function() {
            scroll_pos = $(this).scrollTop();
            if(scroll_pos > 210) {
                $('.text-white').css('color', '#fff');
            } else {
                $('').css('color', '#000');
            }
        });
    })
    </script>

<script>
var close = document.getElementsByClassName("closebtn");
var i;

for (i = 0; i < close.length; i++) {
  close[i].onclick = function(){
    var div = this.parentElement;
    div.style.opacity = "0";
    setTimeout(function(){ div.style.display = "none"; }, 600);
  }
}
</script>